### ISSUE TITLE
Indicate voted status to user

### ISSUE THREAD

**Issue by Brianfit** [xavivives/Uumm#1]
Do you want UI feedback now or later? A proposal that a user has already voted on currently allows a second vote transaction and costs ether, even though it correctly doesn't impact the project status. A change in the vote button to indicate user has already voted would prevent that.

**Comment by xavivives** [comment]
Hi Brian! This feedback is very helpful. Anything you see, don't hesitate
on letting me now.

I'm aware on this.
It is allowed to change the vote. One reason is because the user may have
changed the opinion or made a mistake.
The main reason though is because within the time that a participant has
voted and the time that the proposal is resolved, another proposal may have
been resolved increassing the the 'value points' of the participant.
Allowing to vote again (previous vote is reverted), allows the participant
to do it with all of its value points (including the new ones).

There are a lot of intermidiate states making the UI a little painful. I've
been delaying this kind of bugs prioritizing serious stuff.

But since you mentioned I'll take it as important enough to take action (as
well as the funding).

Thanks again. If you see more problems or have ideas and improvements, you
can also create an 'issue' in the github repository.

Aloha!

**Comment by xavivives** [comment]
The proposals interface has been upgraded, showing more information and handling more states.
The case you described should not be possible anymore
